on:
  push:
    branches:
      - '**'

#name: Test with Code Coverage
name: Benchmark

jobs:
  test:
    name: Run
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest] # no MacOS as it is too slow. need to find another directory
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Run benchmark
        run: cargo bench --bench benchmark -- --warm-up-time 10  --sample-size 300
        
